print('Venligst gi inn et flytall med minst 5 siffer både før og etter .')
num = float(input('Hva er tallet ditt? '))
print(f'Konvertert til heltall med int(): {int(num)}')
print(f'Avrundet til nærmeste heltall: {int(round(num, 0))}')
print(f'Avrundet til to desimaler: {round(num, 2)}')
print(f'Avrundet til fire desimaler: {round(num, 4)}')
print(f'Avrundet til nærmeste tusen: {round(num, -3)}')
print(f'Heltall fra int() konvertert tilbake til flyttall: {float(int(num))}')
